version: '2'

services:
  web-app:
    container_name: contpaqisi_web_app_dev
    environment:
      NODE_ENV: development
      API_HOST: http://localhost:3000/
      API_HOST_NAME: localhost
      API_HOST_PORT: 3000
      FRONT_HOST: http://localhost:4000/
      FRONT_HOST_NAME: localhost
      FRONT_HOST_PORT: 4000
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ../:/var/lib/app
      # prevent mounting node_modules to avoid cross-platform incompatibilities
      - /var/lib/app/node_modules
    entrypoint: /var/lib/app/docker/scripts/startup.dev.sh
